#installed.package("tidyverse")
library(tidyverse)
read_csv("data/gapminder.csv")
gapminder <- read_csv("data/gapminder.csv")
nrow(gapminder)
ncol(gapminder)
colnames(gapminder)
glimpse(gapminder)
ncol(storms)
nrow(storms)
glimpse(storms)
storms
read_csv("data/Result2_explain.csv")
overheat <- read_csv("data/Result2_explain.csv")
nrow(overheat)
ncol(overheat)
overheat
glimpse(overheat)
select(gapminder,year,country,pop)
select(gapminder,3,1,5)
select(gapminder,3:5)
select(overheat,-X8)
select(gapminder,-(3:5))
justpopulation <- select(gapminder,year,country,pop)
justpopulation 
glimpse(gapminder)
select(gapminder,country,year,pop,gdpPercap)
select(gapminder,1,3,5,6)
select(gapminder,-2,-4)
select(gapminder,starts_with("co"))
select(gapminder,contains("e"))
select(gapminder,ends_with("p"))
select(gapminder,population = pop)
rename(gapminder, population = pop)
filter(gapminder, country == "Australia")
filter(gapminder, year >= 1997)
filter(gapminder, continent == "Europe")
filter(gapminder, lifeExp >= 80, gdpPercap >= 30000)
filter(gapminder, lifeExp >= 80 | gdpPercap >= 30000)
